# THIS IS AN EXAMPLE FILE, PLEASE COPY IT TO credentials.yml AND FILL IN YOUR CREDENTIALS
#! IMPORTANT: DO NOT COMMIT YOUR CREDENTIALS TO THE REPOSITORY
GENESIS:
  DESTATIS:
    user: YOUR_USER
    pass: YOUR_PASSWORD

# Structure of the config file
# SERVICE:
#   SUBSERVICE:
#     user: YOUR_USER
#     pass: YOUR_PASSWORD
#     ...