# Genesis database should be used with genesis.py
GENISIS:
  - name: '# of school children by federal state (ger)'
    download: '21111-0010'
    site: DESTATIS
    filename: data/genesis/school_children_by_state
    folder: data/genesis/
    format: csv
    years: "1995-2023"
  - name: '# of school children by school type (ger)'
    download: '21111-0004'
    site: DESTATIS
    filename: data/genesis/school_children_by_type
    folder: data/genesis/
    format: csv
    years: "1995-2023"
  - name: '# of repeaters by state, year, sex, school type'
    download: '21111-0005'
    site: DESTATIS
    filename: data/genesis/number_of_repeaters
    folder: data/genesis/
    format: csv
    years: "1998-2022"
  - name: '# students with special educational support'
    download: '21111-0007'
    site: DESTATIS
    filename: data/genesis/students_with_sepecial_educational_support
    folder: data/genesis/
    format: csv
    years: "2000-2022"
  - name: "# graduates #3"
    download: '21111-0013'
    site: DESTATIS
    filename: data/genesis/graduates_3
    folder: data/genesis/
    format: csv
    years: "2015-2022"
  - name: "# graduates #2"
    download: '21111-0013'
    site: DESTATIS
    filename: data/genesis/graduates_2
    folder: data/genesis/
    format: csv
    years: "2007-2014"
  - name: "# graduates #1"
    download: '21111-0013'
    site: DESTATIS
    filename: data/genesis/graduates_1
    folder: data/genesis/
    format: csv
    years: "1998-2006"




# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: data/abi/
  ext: .zip

# Default datasets (single files with url)
DEFAULT:
  - name: 'Oview destatis german schools 2020/21'
    url: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Schulen/Publikationen/Downloads-Schulen/allgemeinbildende-schulen-2110100217005.xlsx?__blob=publicationFile
    filename: allgemeinbildende-schulen.xlsx
    folder: data/raw/
    format: xlsx
  - name: 'Pisa study data for Germany'
    url: https://github.com/KarylReyne/DataLiteracyWS23/files/13629119/IDEExcelExport-Dec102023-0927PM.xls
    filename: pisa_germany.xls
    folder: data/raw/
    format: xls