# Genesis database should be used with genesis.py
GENISIS:
  - name: '# of school children by federal state (ger)'
    download: '21111-0010'
    site: DESTATIS
    filename: school_children_by_state
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: '# of school children by school type (ger)'
    download: '21111-0004'
    site: DESTATIS
    filename: school_children_by_type
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: '# of repeaters by state, year, sex, school type'
    download: '21111-0005'
    site: DESTATIS
    filename: number_of_repeaters
    folder: genesis/
    format: csv
    years: "1998-2022"

# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: abi/
  ext: .zip

# Default datasets (single files with url)
DEFAULT:
  - name: 'Oview destatis german schools 2020/21'
    url: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Schulen/Publikationen/Downloads-Schulen/allgemeinbildende-schulen-2110100217005.xlsx?__blob=publicationFile
    filename: allgemeinbildende-schulen.xlsx
    folder: other/
    format: xlsx
    parser_args:
      sheet: "Tab. 7.1"
  - name: 'Pisa study data for Germany'
    url: https://github.com/KarylReyne/DataLiteracyWS23/files/13629119/IDEExcelExport-Dec102023-0927PM.xls
    filename: pisa_germany.xls
    folder: other/
    format: xls