# Overall download configuration
CONFIG:
  download_path: data/

# Genesis database should be used with genesis.py
GENESIS:
  # - name: '# of school children by federal state (ger)'
  #   download: '21111-0010'
  #   site: DESTATIS
  #   filename: school_children_by_state
  #   folder: genesis/
  #   format: csv
  #   years: "1995-2023"
  # - name: '# of school children by school type (ger)'
  #   download: '21111-0004'
  #   site: DESTATIS
  #   filename: school_children_by_type
  #   folder: genesis/
  #   format: csv
  #   years: "1995-2023"
  # - name: '# of repeaters by state, year, sex, school type'
  #   download: '21111-0005'
  #   site: DESTATIS
  #   filename: number_of_repeaters
  #   folder: genesis/
  #   format: csv
  #   years: "1998-2022"
  # - name: 'Zensus'
  #   download: '12411-0042' # or 12411-0011
  #   site: DESTATIS
  #   filename: zensus
  #   folder: genesis/
  #   format: csv
  #   years: "1995-2023"
  # - name: 'Zensus-1'
  #   download: '12411-0013' # or 12411-0011
  #   site: DESTATIS
  #   filename: zensus-1
  #   folder: genesis/
  #   format: csv
  #   years: "2014-2023"
  # - name: 'Zensus-2'
  #   download: '12411-0013' # or 12411-0011
  #   site: DESTATIS
  #   filename: zensus-2
  #   folder: genesis/
  #   format: csv
  #   years: "2005-2013"
  # - name: 'Zensus-3'
  #   download: '12411-0013' # or 12411-0011
  #   site: DESTATIS
  #   filename: zensus-3
  #   folder: genesis/
  #   format: csv
  #   years: "1996-2004"

# --- secondary effects (uni) ---
  - name: 'Studierende'
    download: '21311-0001'
    site: DESTATIS
    filename: SecEff_000_studierende
    folder: genesis/
    format: csv
    years: "2010-2023"
  - name: 'Studienberechtigtenquote'
    download: '21381-0013'
    site: DESTATIS
    filename: SecEff_001_studienberechtigtenquote
    folder: genesis/
    format: csv
    years: "2010-2023"
  - name: '# of students per subject'
    download: '21311-0004'
    site: DESTATIS
    filename: SecEff_002_numberOfStudentsPerSubject
    folder: genesis/
    format: csv
    years: "2010-2023"
  - name: '# of passes and fails per subject 8 '
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-8_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2015-2015"  
  - name: '# of passes and fails per subject 7'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-7_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2016-2016"
  - name: '# of passes and fails per subject 6'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-6_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2017-2017"
  - name: '# of passes and fails per subject 5'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-5_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2018-2018"
  - name: '# of passes and fails per subject 4'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-4_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2019-2019"
  - name: '# of passes and fails per subject 3'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-3_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2020-2020"
  - name: '# of passes and fails per subject 2'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-2_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2021-2021"
  - name: '# of passes and fails per subject 1'
    download: '21321-0006'
    site: DESTATIS
    filename: SecEff_003-1_numberOfPassesAndFailsPerSubject
    folder: genesis/
    format: csv
    years: "2022-2023"

# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: abi/
  ext: .zip
  fails:
    target: fails.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0
  grades:
    target: grades.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0

# Default datasets (single files with url)
DEFAULT:
  - name: 'Overview destatis german schools 2020/21'
    url: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Schulen/Publikationen/Downloads-Schulen/allgemeinbildende-schulen-2110100217005.xlsx?__blob=publicationFile
    filename: allgemeinbildende-schulen.xlsx
    folder: other/
    format: xlsx
    parser_args:
      sheet: "Tab. 7.1"
  - name: 'Pisa study data for Germany'
    url: https://github.com/KarylReyne/DataLiteracyWS23/files/13629119/IDEExcelExport-Dec102023-0927PM.xls
    filename: pisa_germany.xls
    folder: other/
    format: xls