# Overall download configuration
CONFIG:
  download_path: data/

# Genesis database should be used with genesis.py
GENESIS:
  - name: '# of repeaters by state, year, sex, school type'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters
    folder: genesis/
    format: csv
    years: "1998-2021"    
  - name: '# students with special educational support'
    download: '21111-0008'
    site: DESTATIS
    filename: students_with_sepecial_educational_support
    folder: genesis/
    format: csv
    years: "2000-2022"
  - name: "# graduates-3"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_3
    folder: genesis/
    format: csv
    years: "2015-2022"
  - name: "# graduates-2"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_2
    folder: genesis/
    format: csv
    years: "2007-2014"
  - name: "# graduates-1"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_1
    folder: genesis/
    format: csv
    years: "1998-2006"




# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: abi/
  ext: .zip
  fails:
    target: fails.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0
  grades:
    target: grades.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0

# Default datasets (single files with url)
DEFAULT:
  - name: 'Overview destatis german schools 2020/21'
    url: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Schulen/Publikationen/Downloads-Schulen/allgemeinbildende-schulen-2110100217005.xlsx?__blob=publicationFile
    filename: allgemeinbildende-schulen.xlsx
    folder: other/
    format: xlsx
    parser_args:
      sheet: "Tab. 7.1"
  - name: 'Pisa study data for Germany'
    url: https://github.com/KarylReyne/DataLiteracyWS23/files/13629119/IDEExcelExport-Dec102023-0927PM.xls
    filename: pisa_germany.xls
    folder: other/
    format: xls