# Overall download configuration
CONFIG:
  download_path: data/

# Genesis database should be used with genesis.py
GENESIS:
  - name: '# special educational needs no gender'
    download: '21111-0007'
    site: DESTATIS
    filename: special_educational_needs_no_gender
    folder: genesis/
    format: csv
    years: "2000-2022"  
  - name: '# of school children by federal state (ger)'
    download: '21111-0010'
    site: DESTATIS
    filename: school_children_by_state
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: '# of school children by school type (ger)'
    download: '21111-0002'
    site: DESTATIS
    filename: school_children_by_type
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: 'Zensus'
    download: '12411-0042' # or 12411-0011
    site: DESTATIS
    filename: zensus
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: 'Zensus-1'
    download: '12411-0013' # or 12411-0011
    site: DESTATIS
    filename: zensus-1
    folder: genesis/
    format: csv
    years: "2014-2023"
  - name: 'Zensus-2'
    download: '12411-0013' # or 12411-0011
    site: DESTATIS
    filename: zensus-2
    folder: genesis/
    format: csv
    years: "2005-2013"
  - name: 'Zensus-3'
    download: '12411-0013' # or 12411-0011
    site: DESTATIS
    filename: zensus-3
    folder: genesis/
    format: csv
    years: "1996-2004"
  - name: 'Budgets of schools by federal state (ger)'
    download: '21711-0010'
    site: DESTATIS
    filename: budgets_by_state
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: 'Budgets per public schools by children by federal state (ger)'
    download: '21711-0011'
    site: DESTATIS
    filename: budgets_by_child_by_state
    folder: genesis/
    format: csv
    years: "1995-2023"
  - name: 'Verbraucherpreisindex by state'
    download: '61111-0010'
    site: DESTATIS
    filename: verbraucherpreisindex_state
    folder: genesis/
    format: csv
    years: "1995-2023"

  - name: '# of repeaters by state, year, sex, school type-1'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_1
    folder: genesis/
    format: csv
    years: "1998-2001"    
  - name: '# of repeaters by state, year, sex, school type-2'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_2
    folder: genesis/
    format: csv
    years: "2002-2005"   
  - name: '# of repeaters by state, year, sex, school type-3'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_3
    folder: genesis/
    format: csv
    years: "2006-2009"
  - name: '# of repeaters by state, year, sex, school type-4'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_4
    folder: genesis/
    format: csv
    years: "2010-2013"
  - name: '# of repeaters by state, year, sex, school type-5'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_5
    folder: genesis/
    format: csv
    years: "2014-2017"
  - name: '# of repeaters by state, year, sex, school type-6'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_6
    folder: genesis/
    format: csv
    years: "2018-2020"
  - name: '# of repeaters by state, year, sex, school type-7'
    download: '21111-0014'
    site: DESTATIS
    filename: number_of_repeaters_7
    folder: genesis/
    format: csv
    years: "2021-2022"  
  - name: '# students with special educational support'
    download: '21111-0008'
    site: DESTATIS
    filename: students_with_sepecial_educational_support
    folder: genesis/
    format: csv
    years: "2000-2022"
  - name: "# graduates-3"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_3
    folder: genesis/
    format: csv
    years: "2015-2022"
  - name: "# graduates-2"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_2
    folder: genesis/
    format: csv
    years: "2007-2014"
  - name: "# graduates-1"
    download: '21111-0013'
    site: DESTATIS
    filename: graduates_1
    folder: genesis/
    format: csv
    years: "1998-2006"



# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: abi/
  ext: .zip
  fails:
    target: fails.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0
  grades:
    target: grades.csv
    read_args:
      sep: ","
      encoding: "utf-8"
      header: [0, 1]
      index_col: 0

# Default datasets (single files with url)
DEFAULT:
  - name: 'Overview destatis german schools 2020/21'
    url: https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bildung-Forschung-Kultur/Schulen/Publikationen/Downloads-Schulen/allgemeinbildende-schulen-2110100217005.xlsx?__blob=publicationFile
    filename: allgemeinbildende-schulen.xlsx
    folder: other/
    format: xlsx
    parser_args:
      sheet: "Tab. 7.1"
  - name: 'Pisa study data for Germany'
    url: https://github.com/KarylReyne/DataLiteracyWS23/files/13629119/IDEExcelExport-Dec102023-0927PM.xls
    filename: pisa_germany.xls
    folder: other/
    format: xls