# Genesis database should be used with genesis.py
GENISIS:
  - name: '# of school children by federal state (ger)'
    download: '21111-0010'
    site: DESTATIS
    filename: data/genesis/school_children_by_state
    folder: data/genesis/
    format: csv
    years: "1995-2023"
  - name: '# of school children by school type (ger)'
    download: '21111-004'
    site: DESTATIS
    filename: data/genesis/school_children_by_type
    folder: data/genesis/
    format: csv
    years: "1995-2023"

# Abitur grades by federal state, should be used with abi.py
ABI:
  years: all
  dir: data/abi/
  ext: .zip
