name: Update README
on:
  workflow_run:
    workflows: ["Build LaTeX document"]
    types:
      - completed
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
        - name: Get workflow run ID
          id: get_run_id
          run: 'echo "::set-output name=run_id::$(curl -s -H \"Authorization: token ${{ secrets.GH_TOKEN }}\" https://api.github.com/repos/KarylReyne/DataLiteracyWS23/actions/workflows/build-pdf.yml/runs | jq \".workflow_runs[0].id\")"'
      
        - name: Get artifact download URL
          id: get_artifact_url
          run: 'echo "::set-output name=artifact_url::$(curl -s -H \"Authorization: token ${{ secrets.GH_TOKEN }}\" https://api.github.com/repos/KarylReyne/DataLiteracyWS23/actions/runs/${{ steps.get_run_id.outputs.run_id }}/artifacts | jq -r \".artifacts[0].archive_download_url\")"'
      
        - name: Update README
          run: |
              sed -i '/^Latest PDF:/d' README.md
              echo "Latest PDF: [Download](https://api.github.com/repos/KarylReyne/DataLiteracyWS23/actions/runs/${{ steps.get_run_id.outputs.run_id }}/artifacts)" >> README.md
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git commit -am "Update README with latest PDF link"
              git push https://${{ secrets.GH_TOKEN }}@github.com/KarylReyne/DataLiteracyWS23.git